version: '3.7'

services:
  api:
    image: 'api'
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: api
    ports:
      - 7000:7000
    env_file: .env
    volumes:
      - ./src:/api/src
    networks:
      - np-network
networks:
  np-network: